<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><link rel="alternate" type="text/html" href="https://example.com"/><title>VPN on Beispielprojekt</title><link>https://example.com/affected/vpn/</link><description>Vorfallshistorie</description><generator>github.com/cstate</generator><language>de</language><lastBuildDate>2021-04-29T15:54:00+00:00</lastBuildDate><updated>2021-04-29T15:54:00+00:00</updated><atom:link href="https://example.com/affected/vpn/index.xml" rel="self" type="application/rss+xml"/><item><title>[Gelöst] Ein Problem</title><link>https://example.com/issues/2021-04-29-some-problem/</link><pubDate>Thu, 29 Apr 2021 15:54:00 +0000</pubDate><guid>https://example.com/issues/2021-04-29-some-problem/</guid><category>2021-04-29 16:10:00</category><description>Was ist passiert
Um 15:54 haben wir einen Ausfall von API und VPN festgestellt. Nach kurzer Zeit stand die Lösung fest: Bei Reinigungsarbeiten hatte ein Mitarbeiter einen Netzwerkstecker versehentlich gezogen und nicht wieder eingesteckt. Der Fehler war schnell behoben.
Gelöst – Alle Dienste laufen wieder Update – Wir arbeiten am Problem (29.4. – 16:00)</description><content type="html">&lt;p>&lt;em>Was ist passiert&lt;/em>&lt;/p>
&lt;p>Um 15:54 haben wir einen Ausfall von API und VPN festgestellt. Nach kurzer Zeit stand die Lösung fest: Bei Reinigungsarbeiten hatte ein Mitarbeiter einen Netzwerkstecker versehentlich gezogen und nicht wieder eingesteckt. Der Fehler war schnell behoben.&lt;/p>
&lt;hr>
&lt;p>&lt;em>Gelöst&lt;/em> – Alle Dienste laufen wieder
&lt;em>Update&lt;/em> – Wir arbeiten am Problem
&lt;span class="faded">(29.4. – 16:00)&lt;/span>
&lt;/p></content></item></channel></rss>